/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/auth/twitch/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login With Twitch */
        get: operations["login_with_twitch_api_v1_auth_twitch_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/twitch/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Twitch Callback */
        get: operations["twitch_callback_api_v1_auth_twitch_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_v1_channels__login__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{login}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel Summary */
        get: operations["get_channel_summary_api_v1_channels__login__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{login}/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channel Follows */
        get: operations["list_channel_follows_api_v1_channels__login__follows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{login}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channel Roles */
        get: operations["list_channel_roles_api_v1_channels__login__roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{login}/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel Ladder */
        get: operations["get_channel_ladder_api_v1_channels__login__ladder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan Job */
        get: operations["get_scan_job_api_v1_scan_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{login}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channel Videos */
        get: operations["list_channel_videos_api_v1_channels__login__videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Video Scan Job */
        post: operations["create_video_scan_job_api_v1_videos__video_id__scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AuthSessionRead */
        AuthSessionRead: {
            /** Authenticated */
            authenticated: boolean;
            user?: components["schemas"]["AuthUserRead"] | null;
        };
        /** AuthUserRead */
        AuthUserRead: {
            /** Twitch Id */
            twitch_id: string;
            /** Login */
            login: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** ChannelRead */
        ChannelRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Twitch Id */
            twitch_id: string | null;
            /** Login */
            login: string;
            /** Display Name */
            display_name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Twitch Created At */
            twitch_created_at: string | null;
            /** Fetched At */
            fetched_at: string | null;
        };
        /** ChannelSummary */
        ChannelSummary: {
            channel: components["schemas"]["ChannelRead"];
            /** Videos Count */
            videos_count: number;
            /** Scanned Videos Count */
            scanned_videos_count: number;
            /** Total Messages */
            total_messages: number;
            /** Unique Chatters */
            unique_chatters: number;
        };
        /** FollowList */
        FollowList: {
            channel: components["schemas"]["ChannelRead"];
            /** Items */
            items: components["schemas"]["FollowRead"][];
            /** Total */
            total: number;
            /** Followers Total */
            followers_total: number | null;
            /** Regions */
            regions: components["schemas"]["FollowRegionRead"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FollowRead */
        FollowRead: {
            /** Twitch Id */
            twitch_id: string;
            /** Login */
            login: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Followed At */
            followed_at: string | null;
            /** Twitch Created At */
            twitch_created_at: string | null;
            /** Language */
            language: string;
        };
        /** FollowRegionRead */
        FollowRegionRead: {
            /** Language */
            language: string;
            /** Count */
            count: number;
            /** Percent */
            percent: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LadderEntry */
        LadderEntry: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: string | null;
            /** User Login */
            user_login: string;
            /** User Display Name */
            user_display_name: string | null;
            /** Message Count */
            message_count: number;
            /** Videos Count */
            videos_count: number;
            /** First Message At */
            first_message_at: string | null;
            /** Last Message At */
            last_message_at: string | null;
        };
        /** LadderRead */
        LadderRead: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Videos Count */
            videos_count: number;
            /** Total Messages */
            total_messages: number;
            /** Unique Chatters */
            unique_chatters: number;
            /** Items */
            items: components["schemas"]["LadderEntry"][];
        };
        /**
         * RoleCategory
         * @enum {string}
         */
        RoleCategory: "mods" | "vips" | "founders" | "artists";
        /** RoleList */
        RoleList: {
            channel: components["schemas"]["ChannelRead"];
            /** Items */
            items: components["schemas"]["RoleRead"][];
            /** Total */
            total: number;
            /** Followers Total */
            followers_total: number | null;
            /** Follows Total */
            follows_total: number | null;
            /** Stats */
            stats: components["schemas"]["RoleStatRead"][];
        };
        /** RoleRead */
        RoleRead: {
            /** Twitch Id */
            twitch_id: string;
            /** Login */
            login: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            category: components["schemas"]["RoleCategory"];
            /** Granted At */
            granted_at: string | null;
            /** Twitch Created At */
            twitch_created_at: string | null;
        };
        /** RoleStatRead */
        RoleStatRead: {
            category: components["schemas"]["RoleCategory"];
            /** Count */
            count: number;
            /** Percent */
            percent: number;
        };
        /** ScanJobRead */
        ScanJobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Kind */
            kind: string;
            status: components["schemas"]["ScanJobStatus"];
            /** Progress Percent */
            progress_percent: number;
            /** Processed Messages */
            processed_messages: number;
            /** Total Messages Estimate */
            total_messages_estimate: number | null;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScanJobStatus
         * @enum {string}
         */
        ScanJobStatus: "pending" | "running" | "completed" | "failed" | "canceled";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoChatScanStatus
         * @enum {string}
         */
        VideoChatScanStatus: "not_scanned" | "pending" | "running" | "completed" | "failed" | "partial";
        /** VideoList */
        VideoList: {
            /** Items */
            items: components["schemas"]["VideoRead"][];
            /** Total */
            total: number;
        };
        /** VideoRead */
        VideoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Twitch Video Id */
            twitch_video_id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Published At */
            published_at: string | null;
            /** View Count */
            view_count: number | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            chat_scan_status: components["schemas"]["VideoChatScanStatus"];
            /** Fetched At */
            fetched_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    login_with_twitch_api_v1_auth_twitch_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    twitch_callback_api_v1_auth_twitch_callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                twitch_ladder_oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                twitch_ladder_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_channel_api_v1_channels__login__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_summary_api_v1_channels__login__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_channel_follows_api_v1_channels__login__follows_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: string | null;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channel_roles_api_v1_channels__login__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_ladder_api_v1_channels__login__ladder_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LadderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_job_api_v1_scan_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channel_videos_api_v1_channels__login__videos_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_video_scan_job_api_v1_videos__video_id__scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
